# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-16 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('descripcion_actividad', models.TextField(blank=True, max_length=400, null=True, verbose_name='Descripción actividad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_comentario', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comuna', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado_tour', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion_tiempo_evaluacion', models.IntegerField(blank=True, default=0, null=True, verbose_name='Puntuación tiempo')),
                ('puntuacion_calidad_evaluacion', models.IntegerField(blank=True, default=0, null=True, verbose_name='Puntuación calidad')),
                ('puntuacion_cumplimiento_evaluacion', models.IntegerField(blank=True, default=0, null=True, verbose_name='Puntuación cumplimiento')),
                ('comentario_evaluacion', models.TextField(blank=True, max_length=400, null=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_favorito', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
            ],
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_guia', models.TextField(blank=True, max_length=400, null=True, verbose_name='Descripción Guia')),
                ('clasificacion_guia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Clasificación')),
                ('rut_guia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rut')),
                ('telefono_guia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Teléfono guia')),
                ('celular_guia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Celular guia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_horario', models.DateTimeField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('fin_horario', models.DateTimeField(blank=True, null=True, verbose_name='Fecha fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupo_inscripcion', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cupo inscripción')),
                ('costo_inscripcion', models.IntegerField(blank=True, default=0, null=True, verbose_name='Costo')),
                ('terminos_servicio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Terminos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
                ('evaluacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaliación', to='cicerotwebapp.Evaluacion', verbose_name='Evaluación')),
            ],
        ),
        migrations.CreateModel(
            name='InstanciaTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_instancia_tour', models.DateTimeField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('fin_instancia_tour', models.DateTimeField(blank=True, null=True, verbose_name='Fecha fin')),
                ('cupo_instancia_tour', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cupo instancia tour')),
                ('costo_instacia_tour', models.IntegerField(blank=True, default=0, null=True, verbose_name='Costo')),
                ('estado_instacia_tour', models.CharField(blank=True, max_length=225, null=True, verbose_name='Estado instancia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_multimedia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('descripcion_multimedia', models.TextField(blank=True, max_length=400, null=True, verbose_name='Descripción')),
                ('formato_multimedia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Formato')),
                ('archivo_multimedia', models.FileField(blank=True, null=True, upload_to='documentos/multimedia/%Y/%m/%d', verbose_name='Archivo multimedia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cicerotwebapp.Actividad', verbose_name='Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pais', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_provincia', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_region', models.CharField(max_length=100, verbose_name='Nombre')),
                ('sigla_region', models.CharField(max_length=100, verbose_name='Sigla')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroGuia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_guia_registro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Guia')),
                ('direccion_representante_legal_registro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Representante legal')),
                ('razon_social_guia_registro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón social')),
                ('representante_legal_guia_registro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Representante legal')),
                ('nombre_fantasia_guia_registro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('es_sello_q_registro', models.BooleanField(default=False, verbose_name='¿Tiene sello Q?')),
                ('tipo_sello_q_registro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo sello')),
                ('inicio_sello_q_registro', models.DateTimeField(blank=True, null=True, verbose_name='Fecha inicio sello Q')),
                ('fin_sello_q_registro', models.DateTimeField(blank=True, null=True, verbose_name='Fecha fin sello Q')),
                ('tipo_personalidad_registro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Personalidad Jurídica')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
                ('usuario', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Roles')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_servicio_tour', models.TextField(blank=True, max_length=400, null=True, verbose_name='Descripción')),
                ('es_pago_servicio_tour', models.BooleanField(default=False, verbose_name='¿Tiene costo el servicio?')),
                ('costo_servicio_tour', models.IntegerField(blank=True, default=0, null=True, verbose_name='Costo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_staff', models.TextField(blank=True, max_length=400, null=True, verbose_name='Descripción')),
                ('cargo_staff', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo Staff')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
                ('usuario_seguido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguido', to=settings.AUTH_USER_MODEL, verbose_name='Seguido')),
                ('usuario_seguidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguidor', to=settings.AUTH_USER_MODEL, verbose_name='Seguidor')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
            ],
        ),
        migrations.CreateModel(
            name='TextoSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_texto_select', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría')),
                ('texto_select', models.CharField(blank=True, max_length=100, null=True, verbose_name='Texto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
            ],
        ),
        migrations.CreateModel(
            name='TipoGuia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_guia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMultimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_multimedia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_servicio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
            ],
        ),
        migrations.CreateModel(
            name='TipoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
            ],
        ),
        migrations.CreateModel(
            name='TipoTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_tour', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tour', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Tour')),
                ('descripcion_tour', models.TextField(blank=True, max_length=400, null=True, verbose_name='Descripción Tour')),
                ('capacidad_tour', models.IntegerField(blank=True, null=True, verbose_name='Capacidad Tour')),
                ('precio_tour', models.IntegerField(blank=True, null=True, verbose_name='Precio Tour')),
                ('es_oferta', models.BooleanField(default=False, verbose_name='¿Tour en oferta?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
                ('comunas', models.ManyToManyField(blank=True, related_name='tour', to='cicerotwebapp.Comuna', verbose_name='Comunas tour')),
                ('estado_tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cicerotwebapp.EstadoTour', verbose_name='Estado Tour')),
                ('guia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='cicerotwebapp.Guia')),
                ('tags', models.ManyToManyField(blank=True, related_name='tour', to='cicerotwebapp.Tag', verbose_name='Tags tour')),
                ('tipo_tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cicerotwebapp.TipoTour', verbose_name='Tipo tour')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_transaccion', models.IntegerField(blank=True, default=0, null=True, verbose_name='Monto transacción')),
                ('codigo_transaccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código transacción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
            ],
        ),
        migrations.CreateModel(
            name='Turista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_turista', models.TextField(blank=True, max_length=400, null=True, verbose_name='Descripción Turista')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cicerotwebapp.Pais', verbose_name='Pais')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='tipo_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cicerotwebapp.TipoTag', verbose_name='Tipo de Tag'),
        ),
        migrations.AddField(
            model_name='serviciotour',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cicerotwebapp.TipoServicio', verbose_name='Tipo servicio'),
        ),
        migrations.AddField(
            model_name='serviciotour',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cicerotwebapp.Tour', verbose_name='Tour'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cicerotwebapp.Region', verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='tipo_multimedia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cicerotwebapp.TipoMultimedia', verbose_name='Tipo multimedia'),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cicerotwebapp.Tour', verbose_name='Tour'),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='instanciatour',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cicerotwebapp.Tour', verbose_name='Tour'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='instancia_tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cicerotwebapp.InstanciaTour', verbose_name='Instancia tour'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='transaccion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacción', to='cicerotwebapp.Transaccion', verbose_name='Transacción'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='turista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cicerotwebapp.Turista', verbose_name='Turista'),
        ),
        migrations.AddField(
            model_name='horario',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cicerotwebapp.Tour', verbose_name='Horario Tour'),
        ),
        migrations.AddField(
            model_name='guia',
            name='registro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guia', to='cicerotwebapp.RegistroGuia', verbose_name='Registro guía'),
        ),
        migrations.AddField(
            model_name='guia',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='guia', to='cicerotwebapp.Tag', verbose_name='Tags guía'),
        ),
        migrations.AddField(
            model_name='guia',
            name='tipos_guia',
            field=models.ManyToManyField(blank=True, related_name='guia', to='cicerotwebapp.TipoGuia', verbose_name='Tipos guía'),
        ),
        migrations.AddField(
            model_name='guia',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cicerotwebapp.Tour', verbose_name='Tour'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='turista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cicerotwebapp.Turista', verbose_name='Turista'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cicerotwebapp.Provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cicerotwebapp.Tour', verbose_name='Tour comentado'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que comenta'),
        ),
    ]
