# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-18 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicerotwebapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('asunto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Asunto')),
                ('mensaje', models.TextField(blank=True, max_length=400, null=True, verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
            ],
        ),
    ]
