# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-19 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicerotwebapp', '0002_mensajecontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='latitud',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='tour',
            name='longitud',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitud'),
        ),
    ]
