INSERT INTO cicerot.cicerotwebapp_provincia (`id`,`nombre_provincia`,`region_id`, `created_at`, `updated_at`)
VALUES
	(1,'Arica',1, NOW(), NOW()),
	(2,'Parinacota',1, NOW(), NOW()),
	(3,'Iquique',2, NOW(), NOW()),
	(4,'El Tamarugal',2, NOW(), NOW()),
	(5,'Antofagasta',3, NOW(), NOW()),
	(6,'El Loa',3, NOW(), NOW()),
	(7,'Tocopilla',3, NOW(), NOW()),
	(8,'Chañaral',4, NOW(), NOW()),
	(9,'Copiapó',4, NOW(), NOW()),
	(10,'Huasco',4, NOW(), NOW()),
	(11,'Choapa',5, NOW(), NOW()),
	(12,'Elqui',5, NOW(), NOW()),
	(13,'Limarí',5, NOW(), NOW()),
	(14,'Isla de Pascua',6, NOW(), NOW()),
	(15,'Los Andes',6, NOW(), NOW()),
	(16,'Petorca',6, NOW(), NOW()),
	(17,'Quillota',6, NOW(), NOW()),
	(18,'San Antonio',6, NOW(), NOW()),
	(19,'San Felipe de Aconcagua',6, NOW(), NOW()),
	(20,'Valparaiso',6, NOW(), NOW()),
	(21,'Chacabuco',7, NOW(), NOW()),
	(22,'Cordillera',7, NOW(), NOW()),
	(23,'Maipo',7, NOW(), NOW()),
	(24,'Melipilla',7, NOW(), NOW()),
	(25,'Santiago',7, NOW(), NOW()),
	(26,'Talagante',7, NOW(), NOW()),
	(27,'Cachapoal',8, NOW(), NOW()),
	(28,'Cardenal Caro',8, NOW(), NOW()),
	(29,'Colchagua',8, NOW(), NOW()),
	(30,'Cauquenes',9, NOW(), NOW()),
	(31,'Curicó',9, NOW(), NOW()),
	(32,'Linares',9, NOW(), NOW()),
	(33,'Talca',9, NOW(), NOW()),
	(34,'Arauco',10, NOW(), NOW()),
	(35,'Bio Bío',10, NOW(), NOW()),
	(36,'Concepción',10, NOW(), NOW()),
	(37,'Ñuble',10, NOW(), NOW()),
	(38,'Cautín',11, NOW(), NOW()),
	(39,'Malleco',11, NOW(), NOW()),
	(40,'Valdivia',12, NOW(), NOW()),
	(41,'Ranco',12, NOW(), NOW()),
	(42,'Chiloé',13, NOW(), NOW()),
	(43,'Llanquihue',13, NOW(), NOW()),
	(44,'Osorno',13, NOW(), NOW()),
	(45,'Palena',13, NOW(), NOW()),
	(46,'Aisén',14, NOW(), NOW()),
	(47,'Capitán Prat',14, NOW(), NOW()),
	(48,'Coihaique',14, NOW(), NOW()),
	(49,'General Carrera',14, NOW(), NOW()),
	(50,'Antártica Chilena',15, NOW(), NOW()),
	(51,'Magallanes',15, NOW(), NOW()),
	(52,'Tierra del Fuego',15, NOW(), NOW()),
	(53,'Última Esperanza',15, NOW(), NOW());
